#! /bin/sh
cc -D_POSIX_C_SOURCE -pedantic -Wstrict-prototypes -Werror -std=c11 -O1 -o autorestart autorestart.c -lcurl
cc -D_POSIX_C_SOURCE -pedantic -Wstrict-prototypes -Werror -std=c11 -O1 -o monitor_ssh monitor_ssh.c -lssh
